services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sinar_apps
      POSTGRES_PASSWORD: "asocvZH23lo6PXx_q5MSaimRILamwahr"
    volumes:
      - sinar_apps_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "-LTUGl1S3TjuYLcAP6WO7JctBv3ApXli"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sinar_apps_test
      POSTGRES_PASSWORD: "PfsZzmuzNH2sdPtIy8vkcgmDsZ6BJjHi"
    volumes:
      - sinar_apps_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "GoBr29P6JQDIaC1VeqAZmLD9lfTJ7W4g"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  sinar_apps_data:
  sinar_apps_test_data:
